config/routes.rb
class FiltroListaProveedores
  FILTROS = %w[categoria tipo ubicacion]
  def self.matches?(request)
    FILTROS.include? request.params[:filtro]
  end
end
class FiltroListaTrabajos
  FILTROS = %w[categoria estatus ubicacion]
  def self.matches?(request)
    FILTROS.include? request.params[:filtro]
  end
end

Ttp::Application.routes.draw do
  mount RailsAdmin::Engine => '/agapitear', :as => 'rails_admin'

  scope :path_names => { :new => "nuevo", :edit => "editar" } do
    scope :path_names => { :sign_in => 'iniciar_sesion', :sign_up => 'registro', :sign_out => 'cerrar_sesion', :password => 'clave', :confirmation => 'verificacion', :edit => 'editar' } do
      devise_for :usuarios, :controllers => { :registrations => 'registrations' }
      devise_for :admins
    end

    devise_scope :usuario do
      get '/solicitante/registro' => 'registrations#new', :usuario => { :perfilable_type => 'Solicitante' }, :as => :new_solicitante_registration
      get '/proveedor/registro' => 'registrations#new', :usuario => { :perfilable_type => 'Proveedor' }, :as => :new_proveedor_registration
      put "/solicitante/verificacion" => "confirmations#confirm", :as => :solicitante_confirm
      put "/proveedor/verificacion" => "confirmations#confirm", :as => :proveedor_confirm
    end

    scope "/solicitante" do
      get     "nuevo-perfil" => "solicitantes#new", :as => "new_solicitante"
      get     "editar-perfil" => "solicitantes#edit", :as => "edit_solicitante"
      get     "no-soy-solicitante" => "solicitantes#no_soy_solicitante", :as => "no_soy_solicitante"
      get     "/" => "solicitantes#panel", :as => :panel_solicitante
    end
    resources :solicitantes, :only => [:create, :update]
    
    scope "/proveedor" do
      get     "nuevo-perfil" => "proveedores#new", :as => "new_proveedor"
      get     "editar-perfil" => "proveedores#edit", :as => "edit_proveedor"
      get     "no-soy-proveedor" => "proveedores#no_soy_proveedor", :as => "no_soy_proveedor"
      get     'categorias' => "proveedores#categorias_de_proveedor", :as => "categorias_de_proveedor"
      put     'categorias(/:id)' => "proveedores#update_categorias_de_proveedor", :as => "update_categorias_de_proveedor"
      get     'ubicaciones' => "proveedores#ubicaciones_de_proveedor", :as => "ubicaciones_de_proveedor"
      put     'ubicaciones(/:id)' => "proveedores#update_ubicaciones_de_proveedor", :as => "update_ubicaciones_de_proveedor"
      get     'enlaces' => "proveedores#enlaces_de_proveedor", :as => "enlaces_de_proveedor"
      put     'enlaces(/:id)' => "proveedores#update_enlaces_de_proveedor", :as => "enlaces_de_proveedor"
      get     "imagen" => "proveedores#imagen", :as => "imagen_proveedor"
      put     "imagen(/:id)" => "proveedores#cambiar_imagen", :as => "cambiar_imagen_proveedor"
      get     "imagenes_galeria" => "imagenes#galeria", :as => "galeria_proveedor"
      put     "imagenes_galeria(/:id)" => "imagenes#editar_galeria", :as => "editar_galeria_proveedor"
      delete  "imagenes_galeria(/:id)" => "imagenes#borrar_galeria", :as => "borrar_galeria_proveedor"
      get     "/" => "proveedores#panel", :as => :panel_proveedor
    end
    scope :proveedores do
      get     'proveedores/:filtro/:valor' => "proveedores#index", :as => "listar_proveedores", :constraints => FiltroListaProveedores
      get     "proveedores/:id" => "proveedores#show", :as => "perfil_proveedor"
    end
    resources :proveedores, :only => [:index, :show, :create, :update]
    
    scope :trabajos do
      get     'trabajos/:filtro/:valor' => "trabajos#index", :as => "listar_trabajos", :constraints => FiltroListaTrabajos
    end
    resources :trabajos do
      member do
        match 'abrir' => "trabajos#abrir_trabajo", :via => [:put, :post]
        match 'cerrar' => "trabajos#cerrar_trabajo", :via => [:put, :post]
        match 'finalizar' => "trabajos#finalizar_trabajo", :via => [:put]
      end
      resources :presupuestos, :shallow => true do
        member do
          match 'aceptar' => "presupuestos#aceptar_presupuesto", :via => [:put, :post]
          match 'rechazar' => "presupuestos#rechazar_presupuesto", :via => [:put, :post]
          match 'enviar_datos' => "presupuestos#datos_de_solicitante_a_proveedor", :via => [:put, :post]
        end
        resources :mensajes, :shallow => true # , :only => [:index, :create, :destroy]
      end
      resources :evaluaciones, :except => [:index, :show, :edit, :destroy], :path => "/", :path_names => { :new => "evaluar" }
    end
    
    resources :categorias do
      get     ":que" => "categorias#reset", :as => "reset_en_categorias"
    end
  
    scope "/ubicaciones_geograficas" do
      get "get_lista_entidades" => "ubicaciones_geograficas#get_lista_entidades"
    end
    resources :ubicaciones_geograficas
    
    scope "/general" do
      get "contacto" => "general#home", :as => "general_contacto"
      get "consejos_proveedor" => "general#consejos_proveedor", :as => "consejos_proveedor"
      get "consejos_solicitante" => "general#consejos_solicitante", :as => "consejos_solicitante"
      get "home" => "general#home", :as => "general_home"
      get "terminos-y-condiciones" => "general#tyc", :as => "general_tyc"
    end
   
  end

  root :to => 'general#home'

  match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/shared/_breadcrumbs.html.erb
        <div id="breadcrumbs" class="offset1 span21">
          <%= render_breadcrumbs %>
        </div>

app/views/layouts/shared/_enlaces_de_sitio.html.erb
<% drop = (controller.send(:_layout) == "landing" ? "dropup" : "dropdown") %>
<div id="enlaces-sitio">
    <ul class="nav nav-pills">
        <li>
            <%= link_to "Solicitudes", trabajos_path %>
        </li>
        <li>
            <%= link_to "Proveedores", proveedores_path %>
        </li>
        <li>
            <%= link_to "Contacto", "https://docs.google.com/forms/d/1RzBhILlcjBDTWt5ZACnaeAHCbbmmmJER3Fbb92NlqL4/viewform", :target => "_blank" %>
        </li>
        <li class="divider hidden-phone">
            &nbsp;&nbsp;&nbsp;
        </li>
        <% if usuario_signed_in? %>
        <li class="<%= drop %>">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= glyph(:user, 'white') %> <%= current_usuario.perfilable.nil? ? current_usuario.email.split('@').first : current_usuario.perfilable.nombre_persona.split(' ').first %> <b class="caret"></b> </a>
            <ul class="dropdown-menu">
                <li>
                    <%= link_to 'Panel', polymorphic_path([:panel,current_usuario.perfilable_type.downcase.to_sym]) %>
                </li>
                <li>
                    <%= link_to 'Salir', destroy_usuario_session_path %>
                </li>
            </ul>
        </li>
        <% else %>
        <li><%= link_to "Iniciar sesión", new_usuario_session_path %></li>
        <li class="<%= drop %>">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Registrarme <i class="caret"></i> </a>
            <ul class="dropdown-menu">
                <li>
                    <%= link_to "Solicitante", new_registration_path("solicitante") %>
                </li>
                <li>
                    <%= link_to "Proveedor", new_registration_path("proveedor") %>
                </li>
            </ul>
        </li>
        <% end %>
    </ul>
</div>

app/views/layouts/shared/_errores.html.erb
<% if flash[:warning] %>
  <p class="alert alert-warning"><%= flash[:notice] %></p>
<% elsif flash[:error] %>
  <p class="alert alert-error"><%= flash[:error] %></p>
<% elsif flash[:info] %>
  <p class="alert alert-info"><%= flash[:info] %></p>
<% elsif flash[:success] %>
  <p class="alert alert-success"><%= flash[:success] %></p>
<% elsif notice %>
  <p class="alert alert-warning"><%= notice %></p>
<% elsif alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>

app/views/layouts/shared/_ga.html.erb
<% unless (defined? resource_name and resource_name.to_s == "admin") or admin_signed_in? %>
    <% if Rails.env.production? %>
    <script>
        // Produccion
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-39702251-1']);
          _gaq.push(['_trackPageview']);
        
          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
    </script>
    <!-- Google Analytics -->
    <script>
        // Produccion
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    
      ga('create', 'UA-39702251-1', 'tentupresupuesto.com.ve');
      ga('send', 'pageview');
    
    </script>
    <!-- End Google Analytics -->
    <% else %>
    <script>
        // Pruebas
        (function(i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] ||
            function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o), m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
    
        ga('create', 'UA-39702251-3', 'tentupresupuesto.com.ve');
        ga('send', 'pageview'); 
    </script>
    <% end %>
<% end %>

app/views/layouts/shared/_mensajes.html.erb
<% 
  if flash[:warning] 
    clase = "alert alert-warning"
    mensaje = flash[:warning]
  elsif flash[:error]
    clase = "alert alert-error"
    mensaje = flash[:error]
  elsif flash[:info]
    clase = "alert alert-info"
    mensaje = flash[:info]
  elsif flash[:success]
    clase = "alert alert-success"
    mensaje = flash[:success]
  elsif notice
    clase = "alert alert-warning"
    mensaje = notice
  elsif alert
    clase = "alert alert-error"
    mensaje = alert
  else
    clase = "hide"
    mensaje= ""
  end 
%>
<div id="mensaje-ttp" class="<%= clase %>"> 
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= mensaje.html_safe %>
</div>

app/views/layouts/shared/_metatags.html.erb
        <meta charset="utf-8">
        <title><%= content_for?(:title) ? yield(:title) : "TenTuPresupuesto: Solicita servicios de reparación y remodelación" %></title>
        <meta name="title" content="TenTuPresupuesto - <%= yield(:title) if content_for?(:title) %>">
        <meta name="description" content="<%= content_for?(:meta_description) ? yield(:meta_description) : 'Servicios de reparación y remodelación: decoracion de interiores, cocinas, baños, plomeria, carpinteria, construccion, impermeabilizacion, jardineria... ¡y más!' %>" >
        <meta name="keywords" content="filtraciones, carpinteros, construcciones, remodelaciones, reparaciones, mecanicos, ascensores, bombas de agua, decoracion de interiores, topes, pisos, puertas, rejas, ventanas, cocinas, baños">
        <meta name="author" content="@MarcoGonzalo">
        <meta name="application-name" content="TenTuPresupuesto">
        <meta name="robots" content="all">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta name="google-site-verification" content="LHZYdYVTJf5atQT3Ye4-gn4xnS26feS3sJdBifmoeuY">
        <%= render 'layouts/shared/ga' %>
        <%= favicon_link_tag image_path('tentu/favicon/apple-touch-icon-144-precomposed.png'), :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
        <%= favicon_link_tag image_path('tentu/favicon/apple-touch-icon-114-precomposed.png'), :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
        <%= favicon_link_tag image_path('tentu/favicon/apple-touch-icon-72-precomposed.png'), :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
        <%= favicon_link_tag image_path('tentu/favicon/apple-touch-icon-precomposed.png'), :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
        <%= favicon_link_tag image_path('tentu/favicon/favicon.png'), :rel => 'shortcut icon' %>
        <%= javascript_include_tag "modernizr" %>

app/views/layouts/shared/_pie_de_pagina.html.erb
<footer id="piedepagina">
    <div class="container">
        <div id="pie" class="span24">
            <div class="container offset1 span21" style="height:100%;">
                <div id="mapa-sitio">
                    <div>
                        <h3 class="sobre-color">Sitio</h3>
                        <ul class="doble">
                            <li>
                                <%= link_to "Inicio", root_path %>
                            </li>
                            <% if usuario_signed_in? %>
                            <li>
                                <%= link_to 'Panel', polymorphic_path([:panel,current_usuario.perfilable_type.downcase]) %>
                            </li>
                            <% else %>
                            <li>
                                <%= link_to "Registro", new_registration_path("solicitante") %>
                            </li>
                            <% end %>
                            <li>
                                <%= link_to "Proveedores", proveedores_path %>
                            </li>
                            <li>
                                <%= link_to "Solicitudes", trabajos_path %>
                            </li>
                            <li>
                                <%= link_to "Contacto", "https://docs.google.com/forms/d/1RzBhILlcjBDTWt5ZACnaeAHCbbmmmJER3Fbb92NlqL4/viewform", :target => "_blank" %>
                            </li>
                            <li>
                                <%= link_to "Términos y Condiciones", general_tyc_path %>
                            </li>
                        </ul>
                    </div>
                </div>
                <div id="logo-pie" class="offset2 span6 hidden-phone"></div>
            </div>
            <ul id="botones-sociales">
                <li id="facebook">
                    <a href="http://www.facebook.com/TenTuPresupuesto" title="TenTuPresupuesto en Facebook"><span>TenTuPresupuesto en Facebook</span></a>
                </li>
                <li id="google">
                    <a href="http://plus.google.com/u/0/b/110823009356675456247" title="TenTuPresupuesto en Google+"><span>TenTuPresupuesto en Google+</span></a>
                </li>
                <li id="twitter">
                    <a href="http://twitter.com/TnTuPresupuesto" title="TenTuPresupuesto en Twitter"><span>@TnTuPresupuesto</span></a>
                </li>
                <li id="youtube">
                    <a href="http://www.youtube.com/user/TenTuPresupuesto" title="TenTuPresupuesto en YouTube"><span>Videos de TenTuPresupuesto</span></a>
                </li>
            </ul>
        </div>
    </div>
</footer>

app/views/layouts/shared/ga.html.erb
<% if Rails.env.production? %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-39702251-1', 'tentupresupuesto.com.ve');
  ga('send', 'pageview');
</script>
<% end %>
<% if Rails.env.staging? %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-39702251-3', 'tentupresupuesto.com.ve');
  ga('send', 'pageview');
</script>
<% end %>