config/routes.rb
class FiltroListaProveedores
  FILTROS = %w[categoria tipo ubicacion]
  def self.matches?(request)
    FILTROS.include? request.params[:filtro]
  end
end
class FiltroListaTrabajos
  FILTROS = %w[categoria estatus ubicacion]
  def self.matches?(request)
    FILTROS.include? request.params[:filtro]
  end
end

Ttp::Application.routes.draw do
  mount RailsAdmin::Engine => '/agapitear', :as => 'rails_admin'

  scope :path_names => { :new => "nuevo", :edit => "editar" } do
    scope :path_names => { :sign_in => 'iniciar_sesion', :sign_up => 'registro', :sign_out => 'cerrar_sesion', :password => 'clave', :confirmation => 'verificacion', :edit => 'editar' } do
      devise_for :usuarios, :controllers => { :registrations => 'registrations' }
      devise_for :admins
    end

    devise_scope :usuario do
      get '/solicitante/registro' => 'registrations#new', :usuario => { :perfilable_type => 'Solicitante' }, :as => :new_solicitante_registration
      get '/proveedor/registro' => 'registrations#new', :usuario => { :perfilable_type => 'Proveedor' }, :as => :new_proveedor_registration
      put "/solicitante/verificacion" => "confirmations#confirm", :as => :solicitante_confirm
      put "/proveedor/verificacion" => "confirmations#confirm", :as => :proveedor_confirm
    end

    scope "/solicitante" do
      get     "nuevo-perfil" => "solicitantes#new", :as => "new_solicitante"
      get     "editar-perfil" => "solicitantes#edit", :as => "edit_solicitante"
      get     "no-soy-solicitante" => "solicitantes#no_soy_solicitante", :as => "no_soy_solicitante"
      get     "/" => "solicitantes#panel", :as => :panel_solicitante
    end
    resources :solicitantes, :only => [:create, :update]
    
    scope "/proveedor" do
      get     "nuevo-perfil" => "proveedores#new", :as => "new_proveedor"
      get     "editar-perfil" => "proveedores#edit", :as => "edit_proveedor"
      get     "no-soy-proveedor" => "proveedores#no_soy_proveedor", :as => "no_soy_proveedor"
      get     'categorias' => "proveedores#categorias_de_proveedor", :as => "categorias_de_proveedor"
      put     'categorias(/:id)' => "proveedores#update_categorias_de_proveedor", :as => "update_categorias_de_proveedor"
      get     'ubicaciones' => "proveedores#ubicaciones_de_proveedor", :as => "ubicaciones_de_proveedor"
      put     'ubicaciones(/:id)' => "proveedores#update_ubicaciones_de_proveedor", :as => "update_ubicaciones_de_proveedor"
      get     'enlaces' => "proveedores#enlaces_de_proveedor", :as => "enlaces_de_proveedor"
      put     'enlaces(/:id)' => "proveedores#update_enlaces_de_proveedor", :as => "enlaces_de_proveedor"
      get     "imagen" => "proveedores#imagen", :as => "imagen_proveedor"
      put     "imagen(/:id)" => "proveedores#cambiar_imagen", :as => "cambiar_imagen_proveedor"
      get     "imagenes_galeria" => "imagenes#galeria", :as => "galeria_proveedor"
      put     "imagenes_galeria(/:id)" => "imagenes#editar_galeria", :as => "editar_galeria_proveedor"
      delete  "imagenes_galeria(/:id)" => "imagenes#borrar_galeria", :as => "borrar_galeria_proveedor"
      get     "/" => "proveedores#panel", :as => :panel_proveedor
    end
    scope :proveedores do
      get     'proveedores/:filtro/:valor' => "proveedores#index", :as => "listar_proveedores", :constraints => FiltroListaProveedores
      get     "proveedores/:id" => "proveedores#show", :as => "perfil_proveedor"
    end
    resources :proveedores, :only => [:index, :show, :create, :update]
    
    scope :trabajos do
      get     'trabajos/:filtro/:valor' => "trabajos#index", :as => "listar_trabajos", :constraints => FiltroListaTrabajos
    end
    resources :trabajos do
      member do
        match 'abrir' => "trabajos#abrir_trabajo", :via => [:put, :post]
        match 'cerrar' => "trabajos#cerrar_trabajo", :via => [:put, :post]
        match 'finalizar' => "trabajos#finalizar_trabajo", :via => [:put]
      end
      resources :presupuestos, :shallow => true do
        member do
          match 'aceptar' => "presupuestos#aceptar_presupuesto", :via => [:put, :post]
          match 'rechazar' => "presupuestos#rechazar_presupuesto", :via => [:put, :post]
          match 'enviar_datos' => "presupuestos#datos_de_solicitante_a_proveedor", :via => [:put, :post]
        end
        resources :mensajes, :shallow => true # , :only => [:index, :create, :destroy]
      end
      resources :evaluaciones, :except => [:index, :show, :edit, :destroy], :path => "/", :path_names => { :new => "evaluar" }
    end
    
    resources :categorias do
      get     ":que" => "categorias#reset", :as => "reset_en_categorias"
    end
  
    scope "/ubicaciones_geograficas" do
      get "get_lista_entidades" => "ubicaciones_geograficas#get_lista_entidades"
    end
    resources :ubicaciones_geograficas
    
    scope "/general" do
      get "contacto" => "general#home", :as => "general_contacto"
      get "consejos_proveedor" => "general#consejos_proveedor", :as => "consejos_proveedor"
      get "consejos_solicitante" => "general#consejos_solicitante", :as => "consejos_solicitante"
      get "home" => "general#home", :as => "general_home"
      get "terminos-y-condiciones" => "general#tyc", :as => "general_tyc"
    end
   
  end

  root :to => 'general#home'

  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/proveedores_controller.rb
# coding: utf-8
class ProveedoresController < ApplicationController
  require 'genericas'
  #before_filter :no_authenticated, :only => [:new, :create]
  before_filter :authenticate_proveedor!, :except => [:index, :show]

################  
######## VISTAS
################

  # GET /proveedores
  # GET /proveedores.json
  def index
    @titulo = "Todos los proveedores"
    unless params[:filtro].nil?
      proveedores = []
      if FiltroListaProveedores::FILTROS.include?(params[:filtro]) and not params[:valor].nil?
        case params[:filtro]
        when "categoria"
          @categoria = Categoria.find(params[:valor])
          proveedores =  @categoria.nil? ? [] : @categoria.proveedores
          @cant_resultados = proveedores.size
          @titulo = @categoria.nombre
        when "tipo"
          existe_tipo = Proveedor::TIPO_EMPRESA.include?(params[:valor])
          @tipo = existe_tipo ? params[:valor].to_s.humanize : nil
          proveedores = existe_tipo ? Proveedor.where(:tipo_proveedor => params[:valor]) : []
          @cant_resultados = proveedores.size
          @titulo = existe_tipo ? @tipo : "Por tipo"
        when "ubicacion"
          @ubicacion = UbicacionGeografica.find(params[:valor])
          unless @ubicacion.nil? or @ubicacion.tipo != 'estado'
            #case @ubicacion.tipo
            #when 'pais'
            #  proveedores = @ubicacion.proveedores_de_pais
            #when 'estado'
              proveedores = @ubicacion.proveedores
            #when 'municipio'
            #  proveedores = @ubicacion.proveedores_de_municipio
            #when 'localidad'
            #  proveedores = @ubicacion.proveedores_de_localidad
            #end
          end
          @cant_resultados = proveedores.size
          @titulo = @ubicacion.tipo.humanize+" "+@ubicacion.nombre
        end
      end
    else
      proveedores = Proveedor.joins(:categorias).order('created_at DESC').uniq
    end
    @cant_resultados = proveedores.size
    @proveedores = proveedores.includes(:localidad,:municipio,:estado).order('created_at DESC').page(params[:p])
    @titulo += " ("+@cant_resultados.to_s+")"
    add_breadcrumb :index, :proveedores_path
    @categorias = Categoria.joins(:proveedores).order('nombre ASC').uniq
    @categorias_meta = ""
    for c in @categorias
      @categorias_meta += c.nombre+", "
    end
    
    @ubicaciones = UbicacionGeografica.where(:tipo => 'estado', :entidad_id => 1)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proveedores }
    end
  end

  # GET /proveedores/1
  # GET /proveedores/1.json
  def show
    @proveedor = Proveedor.find(params[:id])
    @evaluaciones = @proveedor.evaluaciones.includes(:trabajo => :categoria)
    @imagenes = @proveedor.imagenes.includes(:imagenable)
    
    Proveedor.increment_counter(:visitas,@proveedor.id)
    if request.path != proveedor_path(@proveedor)
      redirect_to @proveedor, status: :moved_permanently
    else
      add_breadcrumb :index, :proveedores_path
      add_breadcrumb @proveedor.nombre_empresa
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @proveedor }
      end
    end
  end

  # GET /proveedor/nuevo
  # GET /proveedores/new.json
  def new
    @proveedor = Proveedor.new
    @localidad = ""
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proveedor }
    end
  end

  # GET /proveedor/editar
  def edit
    @proveedor = Proveedor.find(current_usuario.perfilable_id)
    @localidad = @proveedor.localidad ? @proveedor.localidad.nombre : ""
  end

  # GET /proveedor/cambiar-imagen
  def imagen
    @proveedor = Proveedor.find(current_usuario.perfilable_id)
    render "imagen_perfil"
  end

  # GET /proveedor
  def panel
    @presupuestos_presentados = Presupuesto.includes([:trabajo, :mensajes]).where("presupuestos.proveedor_id = ? AND trabajos.estatus = 'buscando'", current_usuario.perfilable_id).order("trabajos.updated_at DESC")
    @trabajos_asignados = Presupuesto.includes([:trabajo, :mensajes]).where("presupuestos.proveedor_id = ? AND trabajos.estatus = 'ejecutando'", current_usuario.perfilable_id).order("trabajos.updated_at DESC")
    @por_evaluar = Trabajo.sin_evaluar.where(:contratado_id => current_usuario.perfilable_id).estatus_finalizado

    render "panel"
  end
  
  # GET /proveedor/categorias
  def categorias_de_proveedor
    @proveedor = Proveedor.find(current_usuario.perfilable_id)
    render "categorias"
  end
  
  # GET /proveedor/ubicaciones
  def ubicaciones_de_proveedor
    @proveedor = Proveedor.find(current_usuario.perfilable_id)
    render "ubicaciones"
  end
  
  # GET /proveedor/enlaces
  def enlaces_de_proveedor
    @proveedor = Proveedor.find(current_usuario.perfilable_id)
    render "enlaces"
  end

################  
######## ACCIONES
################

  # POST /proveedores
  # POST /proveedores.json
  def create
    params[:proveedor][:pais_id] = 1 # Venezuela
    
    @localidad = params[:proveedor][:localidad_id]
    @proveedor = Proveedor.new(params[:proveedor])
    if Genericas::validar_parametros_a_objeto_sin_localidad(@proveedor, params[:proveedor])
      params[:proveedor][:localidad_id] = UbicacionGeografica.buscar_o_crear_id_de_localidad(@localidad,params[:proveedor][:municipio_id])
    end

    @proveedor = Proveedor.new(params[:proveedor])
    
    respond_to do |format|
      if usuario_signed_in?
        if current_usuario.perfilable_id.nil? or current_usuario.perfilable_id <= 0
          if @proveedor.save
            current_usuario.update_attribute('perfilable_id', @proveedor.id)
            
            if Rails.env.production?
              MailchimpController.subscribe(current_usuario.email,'proveedores')
            end
            
            flash[:success] = "Datos de proveedor registrados."
            format.html { redirect_to categorias_de_proveedor_path }
            format.json { render json: @proveedor, status: :created, location: @proveedor }
          else
            flash[:error] = "Ocurrió un error. Revisa el formulario."
            
            format.html { render action: "new" }
            format.json { render json: @proveedor.errors, status: :unprocessable_entity }
          end
        else
          flash[:warning] = 'Ya posee un perfil asociado.'
          
          format.html { render action: "new"  }
          format.json { render json: @proveedor.errors, status: :unprocessable_entity }
        end 
      else
        flash[:info] = 'No ha iniciado sesión.'
        format.html { redirect_to new_usuario_session }
        format.json { render json: @proveedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proveedores/1
  # PUT /proveedores/1.json
  def update
    @proveedor = Proveedor.find(current_usuario.perfilable_id)
    
    params[:proveedor][:pais_id] = 1 # Venezuela
    
    @localidad = params[:proveedor][:localidad_id]
    if Genericas::validar_parametros_a_objeto_sin_localidad(@proveedor, params[:proveedor])
      params[:proveedor][:localidad_id] = UbicacionGeografica.buscar_o_crear_id_de_localidad(@localidad,params[:proveedor][:municipio_id])
    end

    
    respond_to do |format|
      if @proveedor.update_attributes(params[:proveedor])
        flash[:success] = "Perfil actualizado."
        format.html { redirect_to panel_proveedor_path }
        format.json { head :no_content }
      else
        flash[:error] = "Ocurrió un error. Revisa el formulario."
        format.html { render action: "edit" }
        format.json { render json: @proveedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proveedores/1
  # DELETE /proveedores/1.json
  def destroy
    @proveedor = Proveedor.find(params[:id])
    @proveedor.destroy

    respond_to do |format|
      flash[:success] = "Proveedor eliminado."
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  def no_soy_proveedor
    unless current_usuario.perfilable_id.blank?
      redirect_to panel_proveedor_path
      return
    end
    
    current_usuario.update_attribute('perfilable_type','Solicitante')
    redirect_to new_solicitante_path
    return
  end

  def cambiar_imagen
    @proveedor = Proveedor.find(current_usuario.perfilable_id)
    @proveedor.avatar = params[:proveedor][:avatar]
    #@proveedor.avatar = File.open('somewhere')
    #@proveedor.avatar.url # => '/url/to/file.png'
    #@proveedor.avatar.current_path # => 'path/to/file.png'
    #@proveedor.avatar.identifier # => 'file.png'
    respond_to do |format|
      if usuario_signed_in?
        unless current_usuario.perfilable_id.nil? or current_usuario.perfilable_id <= 0
          if @proveedor.save
            flash[:success] = "Imagen de perfil modificada."
            format.html { redirect_to panel_proveedor_path } #render action: "imagen_perfil" }
            format.json { render json: @proveedor, status: :created, location: @proveedor }
          else
            flash[:error] = "Ocurrió un error al modificar la imagen."
            format.html { render action: "imagen_perfil" }
            format.json { render json: @proveedor.errors, status: :unprocessable_entity }
          end
        else
          flash[:warning] = 'No posees un perfil asociado.'
          format.html { redirect_to new_usuario_session }
          format.json { render json: @solicitante.errors, status: :unprocessable_entity }
        end 
      else
        flash[:info] = 'No has iniciado sesión.'
        format.html { redirect_to new_usuario_session }
        format.json { render json: @proveedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proveedor/categorias
  def update_categorias_de_proveedor
    if usuario_signed_in?
      @proveedor = Proveedor.find(current_usuario.perfilable_id)
      if params[:proveedor].nil?
        params[:proveedor] ||= {}
      end
    end

app/helpers/proveedores_helper.rb
module ProveedoresHelper
  def tipos_proveedor
    I18n.t("activerecord.attributes.proveedor.tipos_proveedor").map { |key, value| [ value, key ] }
  end
end

app/views/proveedores/_ficha.html.erb
<% unless p == contratado %>
<div class="ficha">
    <div class="clearfix">
        <div class="imagen pull-right">
            <%= image_tag(p.avatar.mini.url) %>
        </div>
        <div class="proveedor-interesado">
            <span class="nombre" title="<%= p.nombre_empresa %>"><%= truncate(p.nombre_empresa, length:30, separator:' ', omission:'...') %></span>
            <span class="tipo-empresa"><%= t(p.tipo_proveedor, :scope => 'activerecord.attributes.proveedor') %></span>
            <%= raw mostrar_reputacion(p.reputacion, p.valoraciones, "proveedor") %>
        </div>
    </div>
    <div class="botones clearfix">
        <%= link_to "Ver perfil", perfil_proveedor_path(p), :class => 'btn btn-small' %>
        <%= link_to("Ver oferta", presupuesto_path(pre), :class=>"btn btn-small") if es_el_solicitante and pre %>
    </div>
</div>
<% end %>

app/views/proveedores/categorias.html.erb
<%- model_class = Proveedor -%>
<%
 content_for :head do
    stylesheet_link_tag 'categorias', 'proveedores'
  end

  content_for :foot do
    javascript_include_tag 'proveedores'
  end

  content_for :title do
    "Categorías de servicios ofrecidos"
  end
%>
<div class="page-header">
    <h1><%= t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
    :default => "Categorías de #{model_class.model_name.human}") %></h1>
</div>
<p class="centrado">
    Selecciona aquellas categorías que se correspondan con las actividades y servicios que ofreces.
    <br>
    <b>Tu perfil está registrado en <%= @proveedor.categorias.count %></b>.
</p>
<div class="formulario-general categorias">
    <%= form_for @proveedor , :url => update_categorias_de_proveedor_path, :method => :put do |f| %>
    <div id="categorias" class="listado">
        <% for cat in Categoria.find(:all) %>
        <label class="checkbox"> <%= check_box_tag :categoria_ids,
            cat.id,
            @proveedor.categorias.include?(cat),
            :name => @proveedor.class.name.downcase+'[categoria_ids][]' %>
            <%= cat.nombre %> </label>
        <% end %>
    </div>
    <div class="botones">
        <%= link_to "Volver al panel", panel_proveedor_path, :class => 'btn' %> <%= f.submit "Actualizar", :class => 'btn btn-warning' %>
    </div>
    <% end %>
</div>

app/views/proveedores/new.html.erb
<%- model_class = Proveedor -%>
<% 
content_for :head do
  stylesheet_link_tag 'proveedores'
end

content_for :foot do
  javascript_include_tag 'ubicaciones_geograficas', 'proveedores'
end

content_for :title do
  "Crear perfil de proveedor"
end
%>
<script type="text/javascript">var _editando = false;</script>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "Perfil de #{model_class.model_name.human}") %></h1>
</div>
<% if current_usuario.confirmed_at.nil? %>
<div class="alert alert-info alert-block">
    <p>
        <b>¡Verifica tu cuenta de correo!</b><br> 
        Tu dirección de correo electrónico <b><%= current_usuario.email %></b> debe ser verificada. De no hacerlo podría ocasionar que no te lleguen las solicitudes publicadas en tus categorías y el posible bloqueo de tu cuenta.
    </p>
    <p style="text-align: right;"><%= link_to "Verificar mi correo", new_confirmation_path(current_usuario), :class => 'btn btn-info' %></p>
</div>
<% end %>
<p class="centrado">Estás a punto de registrar un perfil como PROVEEDOR de servicios.<br>Si llegaste aquí por error, aún estás a tiempo de <%= link_to "cerrar sesión y crear un perfil de SOLICITANTE", no_soy_proveedor_path %></p>
<%= render :partial => 'form' %>

app/views/proveedores/panel.html.erb
<%
    content_for :head do
        stylesheet_link_tag 'proveedores'
    end
    
    content_for :foot do
        #javascript_include_tag 'trabajos_show'
    end
    
    content_for :title do
        "Panel de Proveedor"
    end
%>
<h1 class="page-header">Panel de proveedor</h1>
<% if current_usuario.confirmed_at.nil? %>
<div class="alert alert-info alert-block">
    <p>
        <b>¡No has verificado tu cuenta de correo!</b><br> 
        Tu dirección de correo electrónico <b><%= current_usuario.email %></b> aún no ha sido verificada. Esto podría ocasionar que no te lleguen las solicitudes publicadas en tus categorías y el posible bloqueo de tu cuenta.
    </p>
    <p style="text-align: right;"><%= link_to "Verificar mi correo", new_confirmation_path(current_usuario), :class => 'btn btn-info' %></p>
</div>
<% end %>
<aside class="span6">
    <div id="menu-panel" class="well">
        <div id="imagen-proveedor" class="img-rounded">
            <%= link_to(image_tag(current_usuario.perfil.avatar.url, :alt => "Cambiar imagen de perfil", :title => "Cambiar imagen de perfil"), imagen_proveedor_path) %>
        </div>
        <ul class="nav nav-list span5">
            <li class="nav-header">
                <i class="icon-white icon-certificate"></i> Usuario
            </li>
            <li>
                <%= link_to "Cambiar clave", edit_usuario_registration_path %>
            </li>
            <li>
                <%= link_to "Ver perfil público", perfil_proveedor_path(current_usuario.perfil) %>
            </li>
            <li class="nav-header">
                <i class="icon-white icon-user"></i> Perfil
            </li>
            <li>
                <%= link_to "Mi imagen", imagen_proveedor_path %>
            </li>
            <li>
                <%= link_to "Mi perfil", edit_proveedor_path %>
            </li>
            <li>
                <%= link_to "Mis categorías", categorias_de_proveedor_path %>
            </li>
            <li>
                <%= link_to "Dónde ofrezco servicio", ubicaciones_de_proveedor_path, {'rel'=>"tooltip", 'title' => 'Indícale a los solicitantes las regiones en las que atiendes solicitudes', "data-placement"=>'right'} %>
            </li>
            <li>
                <%= link_to "Fotos de trabajos", galeria_proveedor_path %>
            </li>
            <li>
                <%= link_to "Mis redes sociales", enlaces_de_proveedor_path, {'rel'=>"tooltip", 'title' => 'Dile a los demás dónde pueden encontrarte en Internet', "data-placement"=>'right'} %>
            </li>
            <li class="nav-header">
                <i class="icon-white icon-list-alt"></i> Actividad
            </li>
            <li>
                <a href="#presupuestos-presentados">Presupuestos presentados <i class="icon-white icon-chevron-right"></i></a>
            </li>
            <li>
                <a href="#trabajos-ejecutando">Trabajos en ejecución <i class="icon-white icon-chevron-right"></i></a>
            </li>
            <li>
                <a href="#trabajos-pendientes">Trabajos por ser evaluados <i class="icon-white icon-chevron-right"></i></a>
            </li>
            <li class="disabled">
                Evaluaciones
            </li>
            <li class="nav-header">
                <i class="icon-white icon-bookmark"></i> Consejos
            </li>
            <li>
                <%= link_to "¿Cómo conseguir clientes?", consejos_proveedor_path(:item => "clientes") %>
            </li>
            <li>
                <%= link_to "¿Cómo hacer un buen presupuesto?", consejos_proveedor_path(:item => "presupuestos") %>
            </li>
            <li class="divider"></li>
            <li class="disabled">
                Estadísticas
            </li>
            <li class="disabled">
                Facturación
            </li>
        </ul>
    </div>
    <div style="text-align:center;">
        <%= render "layouts/shared/publicidad/menu_lateral" %>
    </div>
</aside>
<div class="span16">
    <div class="row">
        <%= link_to "Ver trabajos en mis categorías", listar_trabajos_path('categoria', 'mis-categorias'), :class => 'btn btn-warning pull-right'%>
        <h2 class="page-header">Mis trabajos</h2>
    </div>
    <section id="presupuestos-presentados" class="well">
        <h3>Presupuestos presentados</h3>
        <% if !@presupuestos_presentados.nil? and @presupuestos_presentados.size > 0 %>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Trabajo</th>
                    <th>Precio ofrecido</th>
                    <th>Mensajes</th>
                </tr>
            </thead>
            <tbody>
                <% @presupuestos_presentados.each do |p|
                t = p.trabajo
                %>
                <tr>
                    <td> <%= t.proposito %>
                    <br>
                    <%= link_to "Ver solicitud", trabajo_path(t) %></td>
                    <td style="vertical-align: middle;"><%= link_to((number_to_currency(p.precio_minimo)+" a "+number_to_currency(p.precio_maximo)), p) %></td>
                    <td><%= link_to(t('extras.mensajes', :count => p.cant_mensajes), presupuesto_path(p, :anchor => "mensajes")) %>
                    <br>
                    (<%= p.mensajes.where(:usuario => :solicitante, :visto => false).size %> sin leer)</td>
                </tr>
                <% end %>
            </tbody>
        </table>
        <% else%>
        <p class="text-muted">
            No has presentado presupuestos. Revisa el listado ¡de seguro hay un trabajo para ti!
        </p>
        <% end %>
    </section>
    <section id="trabajos-ejecutando" class="well">
        <h3>Trabajos en ejecución</h3>
        <% unless @trabajos_asignados.nil? or @trabajos_asignados.size < 1 %>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Trabajo y oferta</th>
                    <th>Mensajes</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <% @trabajos_asignados.each do |p|
                t = p.trabajo
                m = p.mensajes
                @trabajo = t
                %>
                <tr>
                    <td>
                        <%= link_to t.proposito, trabajo_path(t) %><br>
                        Presupuesto: <%= link_to((number_to_currency(p.precio_minimo)+" a "+number_to_currency(p.precio_maximo)), p) %>
                    </td>
                    <td style="vertical-align: middle;">
                        <%= link_to(t('extras.mensajes', :count =>p.cant_mensajes), presupuesto_path(p, :anchor => "mensajes")) %><br>
                        (<%= m.where(:usuario => :solicitante, :visto => false).size %> sin leer)
                    </td>
                    <td style="vertical-align: middle; text-align:right;"> 
                        <%= link_to("Finalizar", trabajo_path(t), :id => 'finalizar-trabajo', :class => 'btn btn-success', "data-toggle"=>"modal", "data-backdrop"=>"static") if t.ejecutando? %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
        <% else%>
        <p class="text-muted">
            No tienes trabajos asignados. ¡Interactúa con tus futuros clientes! Eso te ayuda a ganar su confianza.
        </p>
        <% end %>
    </section>
    <section id="trabajos-pendientes" class="well">
        <h3>Trabajos esperando evaluación</h3>
        <% if @por_evaluar.size > 0 %>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Trabajo</th>
                    <th>Presupuesto</th>
                    <th>Mensajes</th>
                </tr>
            </thead>
            <tbody>
                <% @por_evaluar.each do |trabajo|
                p = trabajo.presupuesto_contratado
                m = p.mensajes
                %>
                <tr>
                    <td> <%= trabajo.proposito %>
                    <br>
                    <%= link_to 'Ver solicitud', trabajo %> </td>
                    <td style="vertical-align: middle;"><%= link_to((number_to_currency(p.precio_minimo)+" a "+number_to_currency(p.precio_maximo)), p) %></td>
                    <td> <%= t('extras.mensajes', :count => m.size) %>
                    <br>
                    (<%= m.where(:usuario => :proveedor, :visto => false).size %> sin leer) </td>
                </tr>
                <% end %>
            </tbody>
        </table>
        <% else%>
        <p class="text-muted">
            ¡Excelente! No tienes trabajos sin evaluar
        </p>
        <% end %>
    </section>
</div>