config/routes.rb
class FiltroListaProveedores
  FILTROS = %w[categoria tipo ubicacion]
  def self.matches?(request)
    FILTROS.include? request.params[:filtro]
  end
end
class FiltroListaTrabajos
  FILTROS = %w[categoria estatus ubicacion]
  def self.matches?(request)
    FILTROS.include? request.params[:filtro]
  end
end

Ttp::Application.routes.draw do
  mount RailsAdmin::Engine => '/agapitear', :as => 'rails_admin'

  scope :path_names => { :new => "nuevo", :edit => "editar" } do
    scope :path_names => { :sign_in => 'iniciar_sesion', :sign_up => 'registro', :sign_out => 'cerrar_sesion', :password => 'clave', :confirmation => 'verificacion', :edit => 'editar' } do
      devise_for :usuarios, :controllers => { :registrations => 'registrations' }
      devise_for :admins
    end

    devise_scope :usuario do
      get '/solicitante/registro' => 'registrations#new', :usuario => { :perfilable_type => 'Solicitante' }, :as => :new_solicitante_registration
      get '/proveedor/registro' => 'registrations#new', :usuario => { :perfilable_type => 'Proveedor' }, :as => :new_proveedor_registration
      put "/solicitante/verificacion" => "confirmations#confirm", :as => :solicitante_confirm
      put "/proveedor/verificacion" => "confirmations#confirm", :as => :proveedor_confirm
    end

    scope "/solicitante" do
      get     "nuevo-perfil" => "solicitantes#new", :as => "new_solicitante"
      get     "editar-perfil" => "solicitantes#edit", :as => "edit_solicitante"
      get     "no-soy-solicitante" => "solicitantes#no_soy_solicitante", :as => "no_soy_solicitante"
      get     "/" => "solicitantes#panel", :as => :panel_solicitante
    end
    resources :solicitantes, :only => [:create, :update]
    
    scope "/proveedor" do
      get     "nuevo-perfil" => "proveedores#new", :as => "new_proveedor"
      get     "editar-perfil" => "proveedores#edit", :as => "edit_proveedor"
      get     "no-soy-proveedor" => "proveedores#no_soy_proveedor", :as => "no_soy_proveedor"
      get     'categorias' => "proveedores#categorias_de_proveedor", :as => "categorias_de_proveedor"
      put     'categorias(/:id)' => "proveedores#update_categorias_de_proveedor", :as => "update_categorias_de_proveedor"
      get     'ubicaciones' => "proveedores#ubicaciones_de_proveedor", :as => "ubicaciones_de_proveedor"
      put     'ubicaciones(/:id)' => "proveedores#update_ubicaciones_de_proveedor", :as => "update_ubicaciones_de_proveedor"
      get     'enlaces' => "proveedores#enlaces_de_proveedor", :as => "enlaces_de_proveedor"
      put     'enlaces(/:id)' => "proveedores#update_enlaces_de_proveedor", :as => "enlaces_de_proveedor"
      get     "imagen" => "proveedores#imagen", :as => "imagen_proveedor"
      put     "imagen(/:id)" => "proveedores#cambiar_imagen", :as => "cambiar_imagen_proveedor"
      get     "imagenes_galeria" => "imagenes#galeria", :as => "galeria_proveedor"
      put     "imagenes_galeria(/:id)" => "imagenes#editar_galeria", :as => "editar_galeria_proveedor"
      delete  "imagenes_galeria(/:id)" => "imagenes#borrar_galeria", :as => "borrar_galeria_proveedor"
      get     "/" => "proveedores#panel", :as => :panel_proveedor
    end
    scope :proveedores do
      get     'proveedores/:filtro/:valor' => "proveedores#index", :as => "listar_proveedores", :constraints => FiltroListaProveedores
      get     "proveedores/:id" => "proveedores#show", :as => "perfil_proveedor"
    end
    resources :proveedores, :only => [:index, :show, :create, :update]
    
    scope :trabajos do
      get     'trabajos/:filtro/:valor' => "trabajos#index", :as => "listar_trabajos", :constraints => FiltroListaTrabajos
    end
    resources :trabajos do
      member do
        match 'abrir' => "trabajos#abrir_trabajo", :via => [:put, :post]
        match 'cerrar' => "trabajos#cerrar_trabajo", :via => [:put, :post]
        match 'finalizar' => "trabajos#finalizar_trabajo", :via => [:put]
      end
      resources :presupuestos, :shallow => true do
        member do
          match 'aceptar' => "presupuestos#aceptar_presupuesto", :via => [:put, :post]
          match 'rechazar' => "presupuestos#rechazar_presupuesto", :via => [:put, :post]
          match 'enviar_datos' => "presupuestos#datos_de_solicitante_a_proveedor", :via => [:put, :post]
        end
        resources :mensajes, :shallow => true # , :only => [:index, :create, :destroy]
      end
      resources :evaluaciones, :except => [:index, :show, :edit, :destroy], :path => "/", :path_names => { :new => "evaluar" }
    end
    
    resources :categorias do
      get     ":que" => "categorias#reset", :as => "reset_en_categorias"
    end
  
    scope "/ubicaciones_geograficas" do
      get "get_lista_entidades" => "ubicaciones_geograficas#get_lista_entidades"
    end
    resources :ubicaciones_geograficas
    
    scope "/general" do
      get "contacto" => "general#home", :as => "general_contacto"
      get "consejos_proveedor" => "general#consejos_proveedor", :as => "consejos_proveedor"
      get "consejos_solicitante" => "general#consejos_solicitante", :as => "consejos_solicitante"
      get "home" => "general#home", :as => "general_home"
      get "terminos-y-condiciones" => "general#tyc", :as => "general_tyc"
    end
   
  end

  root :to => 'general#home'

  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/trabajos_controller.rb
# coding: utf-8
class TrabajosController < ApplicationController
  require 'genericas'
  before_filter :authenticate_solicitante!, :except => [:show, :index, :finalizar_trabajo]
  before_filter :authenticate_proveedor!, :only => [:finalizar_trabajo]
  before_filter :find_trabajo, :only => [:show]
  layout :resolve_layout
  add_breadcrumb :index, :trabajos_path

################  
######## VISTAS
################

  # GET /trabajos
  # GET /trabajos.json
  def index
    @titulo = "Todas las solicitudes"
    unless params[:filtro].nil?
      trabajos = []
      if FiltroListaTrabajos::FILTROS.include?(params[:filtro]) and not params[:valor].nil?
        case params[:filtro]
        when "categoria"
          if usuario_signed_in? and current_usuario.tipo?("proveedor") and params[:valor].eql?("mis-categorias")
            
            categorias = current_usuario.perfilable.categorias
            trabajos = Trabajo.where(:categoria_id => categorias)
            @cant_resultados = trabajos.size
            @titulo = "Mis categorías"
          else
            @categoria = Categoria.find(params[:valor])
            trabajos =  @categoria.nil? ? [] : @categoria.trabajos
            @cant_resultados = trabajos.size
            @titulo = @categoria.nombre
          end
        when "estatus"
          existe_estatus = Trabajo::ESTATUS.include?(params[:valor])
          @estatus = Trabajo::ESTATUS.include?(params[:valor]) ? params[:valor].to_s.humanize : nil
          trabajos = existe_estatus ? Trabajo.where(:estatus => params[:valor]) : []
          @cant_resultados = trabajos.size
          @titulo = @estatus
        when "ubicacion"
          @ubicacion = UbicacionGeografica.find(params[:valor])
          trabajos = [] if @ubicacion.nil?
          unless @ubicacion.nil?
            case @ubicacion.tipo
            when 'pais'
              trabajos = @ubicacion.trabajos_de_pais
            when 'estado'
              trabajos = @ubicacion.trabajos_de_estado
            when 'municipio'
              trabajos = @ubicacion.trabajos_de_municipio
            when 'localidad'
              trabajos = @ubicacion.trabajos_de_localidad
            end
          end
          @cant_resultados = trabajos.size
          @titulo = @ubicacion.tipo.humanize+" "+@ubicacion.nombre
        end
      end
    else
      trabajos = Trabajo.order('created_at DESC')
    end
    @cant_resultados = trabajos.size
    @trabajos = trabajos.includes(:categoria,:localidad,:municipio,:estado).order('created_at DESC').page(params[:p])
    @titulo += " ("+@cant_resultados.to_s+")"
    @categorias = Categoria.joins(:trabajos).order('nombre ASC').uniq
    # @categorias_meta = ""
    # for c in @categorias
    #   @categorias_meta += c.nombre+", "
    # end
    
    @ubicaciones = UbicacionGeografica.where(:tipo => 'estado', :entidad_id => 1)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trabajos }
    end
  end

  # GET /trabajos/1
  # GET /trabajos/1.json
  def show
    @trabajo = Trabajo.includes({:presupuestos => :proveedor},:contratado).find(params[:id])
    @es_el_solicitante = (usuario_signed_in? and current_usuario.tipo?("solicitante")) and current_usuario.perfilable_id.eql?(@trabajo.solicitante_id)
    
    if @trabajo.ejecutando? and (usuario_signed_in? and current_usuario.tipo?("proveedor")) 
      @es_el_proveedor = current_usuario.perfilable_id.eql?(@trabajo.contratado_id)
    end
    
    Trabajo.increment_counter(:visitas,@trabajo.id)
    add_breadcrumb @trabajo.proposito
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trabajo }
    end
  end

  # GET /trabajos/new
  # GET /trabajos/new.json
  def new
    perfil = current_usuario.perfil
    
    @trabajo = Trabajo.new
    
    @trabajo.pais_id = perfil.pais_id unless perfil.pais_id.nil?
    @trabajo.estado_id = perfil.estado_id unless perfil.estado_id.nil?
    @trabajo.municipio_id = perfil.municipio_id unless perfil.municipio_id.nil?
    @trabajo.localidad_id = perfil.localidad_id unless perfil.localidad_id.nil?
    @localidad = @trabajo.localidad ? @trabajo.localidad.nombre : ""
    unless perfil.direccion.blank?
      direccion = perfil.direccion
      pto_ref = perfil.punto_referencia.blank? ? "" : ". Punto de referencia: "+perfil.punto_referencia
      @trabajo.direccion = direccion+pto_ref
    end

    add_breadcrumb :new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trabajo }
    end
  end

  # GET /trabajos/1/edit
  def edit
    @trabajo = Trabajo.find(params[:id])
    @localidad = @trabajo.localidad ? @trabajo.localidad.nombre : ""

    add_breadcrumb :edit
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trabajo }
    end
  end

################  
######## ACCIONES
################

  # POST /trabajos
  # POST /trabajos.json
  def create
    params[:trabajo][:pais_id] = 1 # Venezuela
    @localidad = params[:trabajo][:localidad_id]
    @trabajo = Trabajo.new(params[:trabajo])
    if Genericas::validar_parametros_a_objeto_sin_localidad(@trabajo, params[:trabajo])
      params[:trabajo][:localidad_id] = UbicacionGeografica.buscar_o_crear_id_de_localidad(@localidad,params[:trabajo][:municipio_id])
    end

    @trabajo = Trabajo.new(params[:trabajo])
    respond_to do |format|
      @trabajo.solicitante_id = current_usuario.perfilable_id
      if @trabajo.save
        @cant_proveedores = Categoria.find(@trabajo.categoria_id).proveedores.where(:estado_id => @trabajo.estado_id).size
        if @cant_proveedores > 0
          TtpMailer.notificar_solicitud_publicada(@trabajo)
          flash[:success] = "Solicitud publicada los proveedores exitosamente. Hay <b>#{@cant_proveedores} en tu región</b>"
        else
          flash[:info] = "Solicitud publicada los proveedores exitosamente.<br>Por ahora <b>no tenemos proveedores registrados en tu región</b> para tu solicitud. <br>¡Trabajaremos para conseguirlos!"
        end
        format.html { redirect_to @trabajo }
        format.json { render json: @trabajo, status: :created, location: @trabajo }
      else
        flash[:error] = "Ocurrió un error. Revisa el formulario." #+@trabajo.errors.full_messages.to_s
        format.html { render action: "new" }
        format.json { render json: @trabajo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trabajos/1
  # PUT /trabajos/1.json
  def update
    @trabajo = Trabajo.find(params[:id])
    
    params[:trabajo][:pais_id] = 1 # Venezuela
    
    @localidad = params[:trabajo][:localidad_id]
    if Genericas::validar_parametros_a_objeto_sin_localidad(@trabajo, params[:trabajo])
      params[:trabajo][:localidad_id] = UbicacionGeografica.buscar_o_crear_id_de_localidad(@localidad,params[:trabajo][:municipio_id])
    end

    es_el_solicitante = (admin_signed_in? or (@trabajo.solicitante_id == current_usuario.perfilable_id))
    
    respond_to do |format|
      if es_el_solicitante
        if @trabajo.update_attributes(params[:trabajo])
          flash[:success] = "Solicitud actualizada."
          format.html { redirect_to @trabajo }
          format.json { head :no_content }
        else
          flash[:error] = "Ocurrió un error. Revisa el formulario."
          format.html { render action: "edit" }
          format.json { render json: @trabajo.errors, status: :unprocessable_entity }
        end
      else
        flash[:warning] = "Sólo el solicitante puede abrir la solicitud."
        format.html { redirect_to @trabajo }
        format.json { render :json => {tipo_mensaje: :warning, mensaje: flash[:warning]} }
      end
    end
  end

  # DELETE /trabajos/1
  # DELETE /trabajos/1.json
  def destroy
    @trabajo = Trabajo.find(params[:id])
    if admin_signed_in? or (@trabajo.solicitante_id == current_usuario.perfilable_id)
      @trabajo.destroy
    end
    respond_to do |format|
      flash[:success] = "Solicitud eliminada."
      format.html { redirect_to trabajos_url }
      format.json { head :no_content }
    end
  end
  
  def abrir_trabajo
    @trabajo = Trabajo.find(params[:id])
    es_el_solicitante = (@trabajo.solicitante_id == current_usuario.perfilable_id)
    
    respond_to do |format|
      if es_el_solicitante
        if @trabajo.update_attribute('estatus','buscando')
          flash[:success] = "Has reabierto la solicitud para recibir ofertas de proveedores."
          format.html { redirect_to @trabajo }
          format.json { render :json => { presupuesto: @trabajo, tipo_mensaje: :success, mensaje: flash[:success]}}
        else
          flash[:error] = "Ocurrió un error. No pudo abrir la solicitud."
          format.html { redirect_to @trabajo }
          format.json { render :json => { presupuesto: @trabajo.errors, tipo_mensaje: :error, mensaje: flash[:error]} }
        end    
      else
        flash[:warning] = "Sólo el solicitante puede abrir la solicitud."
        format.html { redirect_to @trabajo }
        format.json { render :json => {tipo_mensaje: :warning, mensaje: flash[:warning]} }
      end
    end
  end
  
  def cerrar_trabajo
    @trabajo = Trabajo.find(params[:id])
    es_el_solicitante = (@trabajo.solicitante_id == current_usuario.perfilable_id)
    
    respond_to do |format|
      if es_el_solicitante
        if @trabajo.update_attribute('estatus','cerrado')
          flash[:success] = "Has cerrado la solicitud y ya no recibirá más ofertas de proveedores."
          format.html { redirect_to @trabajo }
          format.json { render :json => { presupuesto: @trabajo, tipo_mensaje: :success, mensaje: flash[:success]}}
        else
          flash[:error] = "Ocurrió un error. No pudo cerrar la solicitud."
          format.html { redirect_to @trabajo }
          format.json { render :json => { presupuesto: @trabajo.errors, tipo_mensaje: :error, mensaje: flash[:error]} }
        end    
      else

app/helpers/trabajos_helper.rb
module TrabajosHelper
  def intenciones
    I18n.t("activerecord.attributes.trabajo.intenciones").map { |key, value| [ value, key ] }
  end
end

app/views/trabajos/_cabecera.html.erb
<header>
  <h1 id="titulo"><%= trabajo.proposito %></h1>
  <div class="cat-m-<%= color %> <%= trabajo.categoria.clase_css %>"></div>
  <section id="datos-solicitud">
    <p>Trabajo en <%= link_to trabajo.categoria.nombre, listar_trabajos_path('categoria', trabajo.categoria.friendly_id) %>. <%= t('extras.presupuestos', :count => cantidad_presupuestos) %>. <i class="icon-eye-open icon-white"></i> <abbr title="<%= t('activerecord.attributes.trabajo.visitas') %>"><%= trabajo.visitas %></abbr></p>
    <p>Ubicado en <%= trabajo.localidad.nombre %>, Municipio <%= trabajo.municipio.nombre %>, Estado <%= trabajo.estado.nombre %>.</p>
    <p>Publicado el <time datetime="<%= l trabajo.created_at, :format => :html5 %>" pubdate="pubdate"><%= l trabajo.created_at, :format => :long %></time>.</p>
  </section>
</header>

app/views/trabajos/_caracteristicas.html.erb
<div id="caracteristicas" class="offset1 span8">
    <h2>La solicitud</h2>
    <br>
    <p class="titulo">
        Categoría:
    </p>
    <p class="texto">
        <%= trabajo.categoria.nombre %>
    </p>
    <p class="titulo">
        Solicitud:
    </p>
    <p class="texto">
        <%= trabajo.proposito %>
    </p>
    <p class="titulo">
        Descripción:
    </p>
    <pre class="texto"><%= trabajo.descripcion %></pre>
</div>

app/views/trabajos/index.html.erb
<%- model_class = Trabajo -%>
<%
 content_for :head do
    stylesheet_link_tag 'categorias', 'trabajos'
  end

  content_for :title do
    "Solicitudes para trabajos en "+@titulo
  end

  content_for :meta_description do
    "Solicitudes para trabajos en "+@titulo
  end

  #  content_for :foot do
  #    javascript_include_tag 'trabajos'
  #  end
%>
<h1 class="page-header">Solicitudes para trabajos</h1>
<aside class="span6">
    <div id="filtros" class="well">
        <% unless usuario_signed_in? and current_usuario.tipo?("proveedor")%>
        <%= link_to "Nueva solicitud", new_trabajo_path, :class => 'btn btn-warning btn-block con-myriad-bold'%>
        <br>
        <% end %>
        <h4>Categorías</h4>
        <div class="listado">
            <ul class=" nav nav-list">
                <li>
                    <b><%= link_to "Todas", trabajos_path %></b>
                </li>
                <% for cat in @categorias %>
                <li>
                    <%= link_to cat.nombre, listar_trabajos_path('categoria', cat.friendly_id) %>
                </li>
                <% end %>
            </ul>
        </div>
        <br>
        <h4>Ubicación</h4>
        <div class="listado">
            <ul class=" nav nav-list">
                <li>
                    <b><%= link_to "Todas", trabajos_path %></b>
                </li>
                <% for ug in @ubicaciones %>
                <li>
                    <%= link_to ug.nombre, listar_trabajos_path('ubicacion', ug.friendly_id) %>
                </li>
                <% end %>
            </ul>
        </div>
        <br>
        <h4>Estatus</h4>
        <div class="listado">
            <ul class=" nav nav-list">
                <li>
                    <b><%= link_to "Todos", trabajos_path %></b>
                </li>
                <% for est in Trabajo::ESTATUS %>
                <% unless est.eql?("cancelado") %>
                <li>
                    <%= link_to est.humanize, listar_trabajos_path('estatus', est) %>
                </li>
                <% end %>
                <% end %>
            </ul>
        </div>
    </div>
    <div style="text-align:center;">
        <%= render "layouts/shared/publicidad/menu_lateral" %>
    </div>
</aside>
<div class="offset1 span15">
    <h2 class="page-header"><%= @titulo %></h2>
    <% if @cant_resultados > 0 %>
    <%= page_entries_info @trabajos %>
    <%= paginate @trabajos, :param_name => 'p' %>
    <% @trabajos.each do |trabajo| %>
    <div class="row trabajo ">
        <h4> <%= link_to trabajo.proposito, trabajo %> </h4>
    <% if trabajo.buscando? %>
        <p class="intencion"><b><%= t('intencion', :scope => 'activerecord.attributes.trabajo') %>:</b> <%= t(trabajo.intencion, :scope => 'activerecord.attributes.trabajo.intenciones') %></p>
    <% end %>
        <section class="datos-solicitud">
            <div class="cat-p-n <%= trabajo.categoria.clase_css %>"></div>
            <div class="datos-en-lista">
                <%= link_to trabajo.categoria.nombre, listar_trabajos_path('categoria', trabajo.categoria.friendly_id) %> | <%= trabajo.estatus.capitalize %> | <%= link_to( t('activerecord.attributes.trabajo.cant_presupuestos'), trabajo_path(trabajo, :anchor => "presupuestos")) %> <span class="badge badge-info"><%= trabajo.cant_presupuestos %></span>
                <br>
                <time datetime="<%= l trabajo.created_at, :format => :html5 %>" pubdate="pubdate">
                    <%= l trabajo.created_at, :format => :abrev %>
                </time> |
                En <%= link_to trabajo.localidad.nombre, listar_trabajos_path('ubicacion', trabajo.localidad.friendly_id) if trabajo.localidad %>, Municipio <%= link_to trabajo.municipio.nombre, listar_trabajos_path('ubicacion', trabajo.municipio.friendly_id) %>, Estado <%= link_to trabajo.estado.nombre, listar_trabajos_path('ubicacion', trabajo.estado.friendly_id) %>.
            </div>
        </section>
        <p class="descripcion">
            <%= truncate(trabajo.descripcion, :length => 250, :separator => ' ') %>
        </p>
    </div>
    <% end %>
    <%= paginate @trabajos, :param_name => 'p' %>
    <% else %>
    <p class="text-muted">
        No se hallaron solicitudes con el criterio seleccionado.
    </p>
    <% end %>
</div>

app/views/trabajos/show.html.erb
<%- model_class = Trabajo -%>
<%
 content_for :head do
    stylesheet_link_tag 'reputacion', 'categorias', 'trabajos'
  end

  content_for :foot do
    javascript_include_tag 'trabajos_show' #'jquery.autoellipsis.min',
  end

  content_for :title do
    "Solicitud: "+@trabajo.proposito
  end

  content_for :meta_description do
      truncate(@trabajo.descripcion, length:150, separator:' ', omission:'... ')+" ["+@trabajo.categoria.nombre+" - Estado "+@trabajo.estado.nombre+", "+@trabajo.pais.nombre+" - "+@trabajo.estatus+"]"
  end

  content_for :article_tag_id do
    "solicitud-trabajo"
  end

  content_for :liston do
    render :partial => 'trabajos/cabecera', :locals => {:trabajo => @trabajo, :cantidad_presupuestos => @trabajo.presupuestos.size, :color => "b"}
  end
%>
<section id="descripcion" class="offset1 span20">
<% if @trabajo.contratado %>
<section id="contratado" class="offset1 span7 pull-right">
    <h2>Proveedor contratado</h2>
    <div class="span6">
        <%= render(:partial => 'proveedores/ficha', :locals => {:p => @trabajo.contratado, :pre => false, :contratado => true, :es_el_solicitante => @es_el_solicitante}) %>
    </div>
</section>
<% end %>
    <h2>Descripci&oacute;n del trabajo solicitado</h2>
<% if @trabajo.buscando? %>
    <p class="intencion"><b><%= t('intencion', :scope => 'activerecord.attributes.trabajo') %>:</b> <%= t(@trabajo.intencion, :scope => 'activerecord.attributes.trabajo.intenciones') %></p>
<% end %>
    <pre><%= @trabajo.descripcion %></pre>
<% unless @trabajo.buscando? %>
    <p><%= "<b>Estatus</b>: ".html_safe+@trabajo.estatus %></p>
<% end %>
<% if @trabajo.ejecutando? %>
    <% if @es_el_proveedor %>
    <h4>Datos del solicitante</h4>
    <dl class="dl-horizontal">
        <% unless @trabajo.solicitante.telefono_local.blank? %>
        <dt>
            <strong>Teléfono Local: </strong>
        </dt>
        <dd>
            <%= @trabajo.solicitante.telefono_local %>
        </dd>
        <% end %>
        <% unless @trabajo.solicitante.telefono_movil.blank? %>
        <dt>
            <strong>Teléfono Móvil </strong>
        </dt>
        <dd>
            <%= @trabajo.solicitante.telefono_movil %>
        </dd>
        <% end %>
        <% unless @trabajo.solicitante.telefono_alt.blank? %>
        <dt>
            <strong>Teléfono Alternativo: </strong>
        </dt>
        <dd>
            <%= @trabajo.solicitante.telefono_alt %>
        </dd>
        <% end %>
    </dl> 
    <% end %>
<% end %>
</section>
<div class="clearfix micro-nota">Ref: <%= @trabajo.id %></div>
<div class="clearfix"></div>
<div class="form-actions">
<% if @es_el_solicitante %>
    <%= link_to "Volver al panel", panel_solicitante_path, :class => 'btn btn-large' %>
    <%= link_to(t('.edit', :default => t("helpers.links.edit")), edit_trabajo_path(@trabajo), :class => 'btn btn-large') if @trabajo.buscando? or @trabajo.cerrado? %>
    <%= link_to "Cerrar solicitud", cerrar_trabajo_path(@trabajo), :method => 'put',
        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Deseas cerrar esta solicitud? Los proveedores no podran ofertarte.')) },
        :id => 'cerrar-solicitud', :class => 'btn btn-large' if @trabajo.buscando? %>
    <%= link_to "Reabrir solicitud", abrir_trabajo_path(@trabajo), :method => 'put',
        :id => 'cerrar-solicitud', :class => 'btn btn-large' if @trabajo.cerrado? %>
    <%= link_to(t('.destroy', :default => t("helpers.links.destroy")),
        trabajo_path(@trabajo),
        :method => 'delete',
        :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Estás seguro de eliminar la oferta?')),
        :class => 'btn btn-danger btn-large') if @trabajo.buscando? or @trabajo.cerrado? %>
    <%= link_to("Evaluar trabajo", new_trabajo_evaluacion_path(@trabajo), :id => 'evaluar-trabajo', :class => 'btn btn-success btn-large') if @trabajo.finalizado? and !@trabajo.evaluacion %>
<% elsif usuario_signed_in? and current_usuario.tipo?("proveedor") %>
    <%= link_to(t('.new', :default => "Ofrece un presupuesto para esta solicitud"),
        new_trabajo_presupuesto_path(@trabajo), :class => 'btn btn-success btn-large') if @trabajo.buscando? %>
    <%= link_to("He finalizado este trabajo", '#modal-finalizado', :id => 'finalizar-trabajo', :class => 'btn btn-success btn-large', "data-toggle"=>"modal", "data-backdrop"=>"static") if @trabajo.ejecutando? and @es_el_proveedor %>
<% elsif usuario_signed_in? and current_usuario.tipo?("solicitante") %>
    <%= link_to(t('.new', :default => "¡Publica una solicitud como esta!"),
        new_trabajo_path, :class => 'btn btn-success btn-large') %>
<% else %>
    <%= link_to t('.new', :default => "Para ofertar presupuestos o publicar solicitudes como esta, regístrate aquí"),
    new_registration_path("proveedor"), :class => 'btn btn-success btn-large' %>
<% end %>
    <%= image_tag "tentu/generales/cargando.gif", {:class => "cargando cargando24", :id => "loading-trabajo"} %>
</div>
<%= render 'trabajos/form_finalizacion' if @trabajo.ejecutando? and @es_el_proveedor %>
<a name="presupuestos"></a>
<% # No se muestra si el trabajo fue asignado y era el unico proveedor
if (@trabajo.presupuestos.size == 1 and not @trabajo.contratado) or @trabajo.presupuestos.size > 1 %>
<section id="proveedores-interesados">
    <h2>Proveedores interesados</h2>
<% if @trabajo.presupuestos %>
    <div id="fichas" class="offset0">
    <% for presupuesto in @trabajo.presupuestos %>
        <%= render(:partial => 'proveedores/ficha', :locals => {:p => presupuesto.proveedor, :pre => presupuesto, :contratado => (@trabajo.contratado and false), :es_el_solicitante => @es_el_solicitante}) %>
    <% end %>
    </div>
<% else %>
    No hay presupuestos presentados
<% end %>
</section>
<% end %>