config/routes.rb
class FiltroListaProveedores
  FILTROS = %w[categoria tipo ubicacion]
  def self.matches?(request)
    FILTROS.include? request.params[:filtro]
  end
end
class FiltroListaTrabajos
  FILTROS = %w[categoria estatus ubicacion]
  def self.matches?(request)
    FILTROS.include? request.params[:filtro]
  end
end

Ttp::Application.routes.draw do
  mount RailsAdmin::Engine => '/agapitear', :as => 'rails_admin'

  scope :path_names => { :new => "nuevo", :edit => "editar" } do
    scope :path_names => { :sign_in => 'iniciar_sesion', :sign_up => 'registro', :sign_out => 'cerrar_sesion', :password => 'clave', :confirmation => 'verificacion', :edit => 'editar' } do
      devise_for :usuarios, :controllers => { :registrations => 'registrations' }
      devise_for :admins
    end

    devise_scope :usuario do
      get '/solicitante/registro' => 'registrations#new', :usuario => { :perfilable_type => 'Solicitante' }, :as => :new_solicitante_registration
      get '/proveedor/registro' => 'registrations#new', :usuario => { :perfilable_type => 'Proveedor' }, :as => :new_proveedor_registration
      put "/solicitante/verificacion" => "confirmations#confirm", :as => :solicitante_confirm
      put "/proveedor/verificacion" => "confirmations#confirm", :as => :proveedor_confirm
    end

    scope "/solicitante" do
      get     "nuevo-perfil" => "solicitantes#new", :as => "new_solicitante"
      get     "editar-perfil" => "solicitantes#edit", :as => "edit_solicitante"
      get     "no-soy-solicitante" => "solicitantes#no_soy_solicitante", :as => "no_soy_solicitante"
      get     "/" => "solicitantes#panel", :as => :panel_solicitante
    end
    resources :solicitantes, :only => [:create, :update]
    
    scope "/proveedor" do
      get     "nuevo-perfil" => "proveedores#new", :as => "new_proveedor"
      get     "editar-perfil" => "proveedores#edit", :as => "edit_proveedor"
      get     "no-soy-proveedor" => "proveedores#no_soy_proveedor", :as => "no_soy_proveedor"
      get     'categorias' => "proveedores#categorias_de_proveedor", :as => "categorias_de_proveedor"
      put     'categorias(/:id)' => "proveedores#update_categorias_de_proveedor", :as => "update_categorias_de_proveedor"
      get     'ubicaciones' => "proveedores#ubicaciones_de_proveedor", :as => "ubicaciones_de_proveedor"
      put     'ubicaciones(/:id)' => "proveedores#update_ubicaciones_de_proveedor", :as => "update_ubicaciones_de_proveedor"
      get     'enlaces' => "proveedores#enlaces_de_proveedor", :as => "enlaces_de_proveedor"
      put     'enlaces(/:id)' => "proveedores#update_enlaces_de_proveedor", :as => "enlaces_de_proveedor"
      get     "imagen" => "proveedores#imagen", :as => "imagen_proveedor"
      put     "imagen(/:id)" => "proveedores#cambiar_imagen", :as => "cambiar_imagen_proveedor"
      get     "imagenes_galeria" => "imagenes#galeria", :as => "galeria_proveedor"
      put     "imagenes_galeria(/:id)" => "imagenes#editar_galeria", :as => "editar_galeria_proveedor"
      delete  "imagenes_galeria(/:id)" => "imagenes#borrar_galeria", :as => "borrar_galeria_proveedor"
      get     "/" => "proveedores#panel", :as => :panel_proveedor
    end
    scope :proveedores do
      get     'proveedores/:filtro/:valor' => "proveedores#index", :as => "listar_proveedores", :constraints => FiltroListaProveedores
      get     "proveedores/:id" => "proveedores#show", :as => "perfil_proveedor"
    end
    resources :proveedores, :only => [:index, :show, :create, :update]
    
    scope :trabajos do
      get     'trabajos/:filtro/:valor' => "trabajos#index", :as => "listar_trabajos", :constraints => FiltroListaTrabajos
    end
    resources :trabajos do
      member do
        match 'abrir' => "trabajos#abrir_trabajo", :via => [:put, :post]
        match 'cerrar' => "trabajos#cerrar_trabajo", :via => [:put, :post]
        match 'finalizar' => "trabajos#finalizar_trabajo", :via => [:put]
      end
      resources :presupuestos, :shallow => true do
        member do
          match 'aceptar' => "presupuestos#aceptar_presupuesto", :via => [:put, :post]
          match 'rechazar' => "presupuestos#rechazar_presupuesto", :via => [:put, :post]
          match 'enviar_datos' => "presupuestos#datos_de_solicitante_a_proveedor", :via => [:put, :post]
        end
        resources :mensajes, :shallow => true # , :only => [:index, :create, :destroy]
      end
      resources :evaluaciones, :except => [:index, :show, :edit, :destroy], :path => "/", :path_names => { :new => "evaluar" }
    end
    
    resources :categorias do
      get     ":que" => "categorias#reset", :as => "reset_en_categorias"
    end
  
    scope "/ubicaciones_geograficas" do
      get "get_lista_entidades" => "ubicaciones_geograficas#get_lista_entidades"
    end
    resources :ubicaciones_geograficas
    
    scope "/general" do
      get "contacto" => "general#home", :as => "general_contacto"
      get "consejos_proveedor" => "general#consejos_proveedor", :as => "consejos_proveedor"
      get "consejos_solicitante" => "general#consejos_solicitante", :as => "consejos_solicitante"
      get "home" => "general#home", :as => "general_home"
      get "terminos-y-condiciones" => "general#tyc", :as => "general_tyc"
    end
   
  end

  root :to => 'general#home'

  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/solicitantes_controller.rb
# coding: utf-8
class SolicitantesController < ApplicationController
  require 'genericas'
  #before_filter :no_authenticated, :only => [:new, :create]
  before_filter :authenticate_solicitante!
  # GET /solicitantes
  # GET /solicitantes.json
  def index
    @solicitantes = Solicitante.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @solicitantes }
    end
  end

  # GET /solicitantes/1
  # GET /solicitantes/1.json
  def show
    @solicitante = current_usuario.datos_y_perfil
    
    add_breadcrumb :panel, panel_solicitante_path
    add_breadcrumb :show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @solicitante }
    end
  end

  # GET /solicitantes/new
  # GET /solicitantes/new.json
  def new
    @solicitante = Solicitante.new
    @localidad = ""
    
    add_breadcrumb :panel, panel_solicitante_path
    add_breadcrumb :new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @solicitante }
    end
  end

  # GET /solicitantes/1/edit
  def edit
    @solicitante = Solicitante.find(current_usuario.perfilable_id)
    @localidad = @solicitante.localidad ? @solicitante.localidad.nombre : ""
    
    add_breadcrumb :panel, panel_solicitante_path
    add_breadcrumb :edit
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @solicitante }
    end
  end
  
  def panel
    @solicitudes = Trabajo.where(:solicitante_id => current_usuario.perfilable_id).includes(:presupuestos).estatus_buscando
    @en_ejecucion = Trabajo.where(:solicitante_id => current_usuario.perfilable_id).estatus_ejecutando
    @por_evaluar = Trabajo.sin_evaluar.where(:solicitante_id => current_usuario.perfilable_id).estatus_finalizado

    render "panel"
  end

################  
######## ACCIONES
################

  # POST /solicitantes
  # POST /solicitantes.json
  def create
    params[:solicitante][:pais_id] = 1 # Venezuela
    
    @localidad = params[:solicitante][:localidad_id]
    @solicitante = Solicitante.new(params[:solicitante])
    if Genericas::validar_parametros_a_objeto_sin_localidad(@solicitante, params[:solicitante])
      params[:solicitante][:localidad_id] = UbicacionGeografica.buscar_o_crear_id_de_localidad(@localidad,params[:solicitante][:municipio_id])
    end
    @solicitante = Solicitante.new(params[:solicitante])
    
    respond_to do |format|
      if usuario_signed_in?
        if current_usuario.perfilable_id.nil? or current_usuario.perfilable_id <= 0
          if @solicitante.save
            current_usuario.update_attribute('perfilable_id', @solicitante.id)
            
            if Rails.env.production?
              MailchimpController.subscribe(current_usuario.email,'solicitantes')
            end
            
            flash[:success] = "Datos de solicitante registrados."
            format.html { redirect_to panel_solicitante_path }
            format.json { render json: @solicitante, status: :created, location: @solicitante }
          else
            flash[:error] = "Ocurrió un error. Revisa el formulario."
            format.html { render action: "new" }
            format.json { render json: @solicitante.errors, status: :unprocessable_entity }
          end
        else
          flash[:warning] = 'Ya posee un perfil asociado.'
          format.html { render action: "new" }
          format.json { render json: @solicitante.errors, status: :unprocessable_entity }
        end
      else
        flash[:info] = 'No ha iniciado sesión.'
        format.html { redirect_to new_proveedor_session }
        format.json { render json: @proveedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /solicitantes/1
  # PUT /solicitantes/1.json
  def update
    @solicitante = Solicitante.find(current_usuario.perfilable_id)

    params[:solicitante][:pais_id] = 1 # Venezuela
    
    @localidad = params[:solicitante][:localidad_id]
    if Genericas::validar_parametros_a_objeto_sin_localidad(@solicitante, params[:solicitante])
      params[:solicitante][:localidad_id] = UbicacionGeografica.buscar_o_crear_id_de_localidad(@localidad,params[:solicitante][:municipio_id])
    end
    
    respond_to do |format|
      if @solicitante.update_attributes(params[:solicitante])
        flash[:success] = "Perfil actualizado."
        format.html { redirect_to panel_solicitante_path }
        format.json { head :no_content }
      else
        flash[:error] = "Ocurrió un error. Revisa el formulario."
        format.html { render action: "edit" }
        format.json { render json: @solicitante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solicitantes/1
  # DELETE /solicitantes/1.json
  def destroy
    @solicitante = Solicitante.find(params[:id])
    @solicitante.destroy

    respond_to do |format|
      flash[:success] = "Solicitante eliminado."
      format.html { redirect_to solicitantes_url }
      format.json { head :no_content }
    end
  end

  def no_soy_solicitante
    unless current_usuario.perfilable_id.blank?
      redirect_to panel_solicitante_path 
      return
    end
    
    current_usuario.update_attribute('perfilable_type','Proveedor')
    redirect_to new_proveedor_path
    return
  end

end

app/helpers/solicitantes_helper.rb
module SolicitantesHelper
end

app/views/solicitantes/_form.html.erb
<div class="formulario-general offset1 span9">
    <%= simple_form_for @solicitante do |f| %>
        <span class="help-block">* Indica campo obligatorio</span>
        <fieldset>
            <legend>
                Datos de contacto
            </legend>
            <p>
                (Ser&aacute; entregado al proveedor si apruebas su presupuesto)
            </p>
            <%= f.input :nombre_persona, :placeholder => 'Ej.: Pedro Pérez' %>
            <%= f.input :telefono_movil, :placeholder => 'Ej.: 04162232323', :required => true %>
            <%= f.input :telefono_local, :placeholder => 'Ej.: 02122561515' %>
            <%= f.input :telefono_alt %>
            <% unless @solicitante.new_record? %>
                <%= f.input :sexo do %>
                    <%= f.select(:sexo, SEXO, {:prompt => 'Selecciona'}) %>
                <% end %>
                <%= f.input :fecha_nacimiento, :end_year => Time.now.year - 85, :start_year => Time.now.year - 18, :class => 'date_field' %>
            <% end %>
        </fieldset>
        <fieldset>
            <legend>
                Datos de ubicaci&oacute;n
            </legend>
            <p>
                (Facilita la publicaci&oacute;n de solicitudes)
            </p>
    
            <%= f.input :pais, :required => true do %>
                <%= select_entidad(:solicitante,:pais_id,nil,"pais") %>
            <% end %>
    
            <%= f.input :estado, :required => true do %>
                <%= select_entidad(:solicitante,:estado_id,1,"estado") %><%= image_tag "tentu/generales/cargando.gif", {:class => "cargando", :id => "loadingestado"} %>
            <% end %>
    
            <%= f.input :municipio, :required => true do %>
                <%= select_entidad(:solicitante,:municipio_id,@solicitante.estado_id,"municipio") %><%= image_tag "tentu/generales/cargando.gif", {:class => "cargando", :id => "loadingmunicipio"} %>
            <% end %>
            
            <%= f.input :localidad, :required => true do %>
                <%= text_entidad(:solicitante,:localidad_id,@localidad) %><%= image_tag "tentu/generales/cargando.gif", {:class => "cargando", :id => "loadinglocalidad"} %>
            <% end %>
            <%= f.input :direccion, :as => :text %>
            <%= f.input :punto_referencia, :placeholder => 'Ej.: Diagonal al puesto de bomberos' %>
        </fieldset>
        <div class="botones">
            <%= f.submit "Guardar perfil", :disable_with => "Enviando...", :class => 'btn btn-warning' %>
        </div>
    <% end %>
</div>
<div id="caracteristicas" class="offset1 span10">
    <hr>
    <div>
        <h4>&iquest;Por qué debo dar mis números de teléfono?</h4>
        <p>
            El número de teléfono es importante para establecer la comunicación final con el proveedor que has decidido contratar. También nos permitirá contactarte sólo si es estrictamente necesario.
        </p>
    </div>
    <div>
        <h4>&iquest;Por qué debo indicar mi ubicación?</h4>
        <p>
            Esta información se colocará automáticamente en el formulario de publicación de solicitudes, facilitándote el proceso. Si el trabajo que vas a contratar es en otro lugar, siempre podrás cambiar la dirección al publicar la solicitud.
        </p>
    </div>
    <div>
        <h4>&iquest;Esta información será pública?</h4>
        <p>
            No. Los números telefónicos y los datos de ubicación exacta serán entregados sólo a aquellos proveedores indiques que contratarás. Al publicar una solicitud sólo se indicará el estado, municipio y localidad de la solicitud, nunca tu dirección exacta.
        </p>
    </div>
    <hr>
</div>

app/views/solicitantes/edit.html.erb
<% content_for :foot do %>
  <%= javascript_include_tag 'ubicaciones_geograficas' %>
  <%= javascript_include_tag 'solicitantes' %>
  <script type="text/javascript">var _editando = true;</script>
<% end %>
<%- model_class = Solicitante -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Editar perfil de #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/solicitantes/index.html.erb
<%- model_class = Solicitante -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:cedula) %></th>
      <th><%= model_class.human_attribute_name(:direccion) %></th>
      <th><%= model_class.human_attribute_name(:punto_referencia) %></th>
      <th><%= model_class.human_attribute_name(:solicitudes_realizadas) %></th>
      <th><%= model_class.human_attribute_name(:trabajos_recibidos) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @solicitantes.each do |solicitante| %>
      <tr>
        <td><%= link_to solicitante.id, solicitante_path(solicitante) %></td>
        <td><%= solicitante.cedula %></td>
        <td><%= solicitante.direccion %></td>
        <td><%= solicitante.punto_referencia %></td>
        <td><%= solicitante.solicitudes_realizadas %></td>
        <td><%= solicitante.trabajos_recibidos %></td>
        <td><%=l solicitante.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_solicitante_path(solicitante), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      solicitante_path(solicitante),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_solicitante_path,
            :class => 'btn btn-primary' %>

app/views/solicitantes/new.html.erb
<%- model_class = Solicitante -%>
<% 
content_for :head do
  stylesheet_link_tag 'solicitantes'
end

content_for :foot do
  javascript_include_tag 'ubicaciones_geograficas', 'solicitantes'
end

content_for :title do
  "Crear perfil de solicitante"
end
%>
<script type="text/javascript">var _editando = false;</script>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "Perfil de #{model_class.model_name.human}") %></h1>
</div>
<% if current_usuario.confirmed_at.nil? %>
<div class="alert alert-info alert-block">
    <p>
        <b>¡Verifica tu cuenta de correo!</b><br> 
        Tu dirección de correo electrónico <b><%= current_usuario.email %></b> debe ser verificada. De no hacerlo podría ocasionar que no te lleguen las notificaciones al recibir un presupuesto y el posible bloqueo de tu cuenta dentro de 30 minutos.        
    </p>
    <p style="text-align: right;"><%= link_to "Verificar mi correo", new_confirmation_path(current_usuario), :class => 'btn btn-info' %></p>
</div>
<% end %>
<p class="centrado">Estás a punto de registrar un perfil como SOLICITANTE de servicios.<br>Si llegaste aquí por error, aún estás a tiempo de <%= link_to "cerrar sesión y crear un perfil de PROVEEDOR", no_soy_solicitante_path %></p>
<%= render :partial => 'form' %>

app/views/solicitantes/panel.html.erb
<%
    content_for :head do
        stylesheet_link_tag 'solicitantes'
    end
    
    content_for :foot do
    #javascript_include_tag 'trabajos_show'
    end
    
    content_for :title do
        "Panel de Solicitante"
    end
%>
<h1 class="page-header">Panel de solicitante</h1>
<% if current_usuario.confirmed_at.nil? %>
<div class="alert alert-info alert-block">
    <p>
        <b>¡No has verificado tu cuenta de correo!</b><br> 
        Tu dirección de correo electrónico <b><%= current_usuario.email %></b> aún no ha sido verificada. Esto podría ocasionar que no te lleguen las notificaciones al recibir un presupuesto y el posible bloqueo de tu cuenta.        
    </p>
    <p style="text-align: right;"><%= link_to "Verificar mi correo", new_confirmation_path(current_usuario), :class => 'btn btn-info' %></p>
</div>
<% end %>
<div class="alert alert-info alert-block hide">
    <h4>¡Ayúdanos a mejorar!</h2>
    <p>
        Estamos realizando una encuesta a todos nuestros usuarios solicitantes para conocer acerca de su experiencia con TenTuPresupuesto.
        <u>No te llevará más de un minuto</u> responderla y será de muchísima ayuda para ofrecerte un mejor sevicio. <i>¡Gracias!</i>
    </p>
    <p style="text-align: right;"><a href="http://bit.ly/1cfpSOC" class="btn btn-info">Participar en la encuesta</a></p>
</div>
<aside class="span6">
    <div id="menu-panel" class="well">
        <ul class="nav nav-list">
            <li class="nav-header">
                <i class="icon-white icon-user"></i> Usuario
            </li>
            <li>
                <%= link_to "Cambiar clave", edit_usuario_registration_path %>
            </li>
            <li>
                <%= link_to "Editar perfil", edit_solicitante_path %>
            </li>
            <li class="divider"></li>
            <li class="nav-header">
                <i class="icon-white  icon-list-alt"></i> Actividad
            </li>
            <li>
                <a href="#solicitudes-abiertas">Solicitudes abiertas <i class="icon-white icon-chevron-right"></i></a>
            </li>
            <li>
                <a href="#trabajos-ejecutando">Trabajos ejecutándose <i class="icon-white icon-chevron-right"></i></a>
            </li>
            <li>
                <a href="#trabajos-pendientes">Trabajos por evaluar <i class="icon-white icon-chevron-right"></i></a>
            </li>
            <li class="nav-header">
                <i class="icon-white icon-bookmark"></i> Consejos
            </li>
            <li>
                <%= link_to "¿Cómo hacer una buena solicitud?", consejos_solicitante_path(:item => "solicitudes") %>
            </li>
            <li class="divider"></li>
            <li class="disabled">
                Estadísticas
            </li>
        </ul>
    </div>
    <%= render "layouts/shared/publicidad/menu_lateral" %>
</aside>
<div class="span16">
    <div class="row">
        <%= link_to "Publicar una nueva solicitud", new_trabajo_path, :class => 'btn btn-warning pull-right'%>
        <h2 class="page-header">Mis solicitudes</h2>
    </div>
    <section id="solicitudes-abiertas" class="well">
        <h3>Solicitudes abiertas</h3>
        <% if @solicitudes.size > 0 %>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Trabajo</th>
                    <th>Presupuestos</th>
                    <th>Total de Mensajes</th>
                </tr>
            </thead>
            <tbody>
                <% @solicitudes.each do |trabajo|
                mensajes = Mensaje.where(:presupuesto_id => trabajo.presupuestos)
                %>
                <tr>
                    <td><%= trabajo.proposito %>
                    <br>
                    <%= link_to 'Ver solicitud', trabajo %></td>
                    <td style="vertical-align: middle;"> <%= link_to t('extras.presupuestos', :count => trabajo.cant_presupuestos), trabajo_presupuestos_path(trabajo) %> </td>
                    <td> <%= t('extras.mensajes', :count => mensajes.size) %>
                    <br>
                    (<%= mensajes.where(:usuario => :proveedor, :visto => false).size %> sin leer) </td>
                </tr>
                <% end %>
            </tbody>
        </table>
        <% else%>
        <p class="text-muted">
            No tienes solicitudes esperando presupuestos.
        </p>
        <% end %>
    </section>
    <section id="trabajos-ejecutando" class="well">
        <h3>Trabajos en ejecución</h3>
        <% if @en_ejecucion.size > 0 %>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Trabajo</th>
                    <th>Presupuesto</th>
                    <th>Mensajes</th>
                </tr>
            </thead>
            <tbody>
                <% @en_ejecucion.each do |trabajo|
                p = trabajo.presupuesto_contratado
                m = p.mensajes
                %>
                <tr>
                    <td>
                    <p>
                        <%= trabajo.proposito %>
                    </p>
                    <p>
                        <%= link_to 'Ver solicitud', trabajo %>
                    </p></td>
                    <td>
                    <p>
                        <%= link_to((number_to_currency(p.precio_minimo)+" a "+number_to_currency(p.precio_maximo)), p) %>
                    </p>
                    <p>
                        Por <%= link_to p.proveedor.nombre_empresa, proveedor_path(p.proveedor) %>
                    </p></td>
                    <td>
                    <p>
                        <%= link_to t('extras.mensajes', :count => p.cant_mensajes), presupuesto_path(p, :anchor => "mensajes") %>
                    </p>
                    <p>
                        (<%= m.where(:usuario => :proveedor, :visto => false).size %> sin leer)
                    </p></td>
                </tr>
                <% end %>
            </tbody>
        </table>
        <% else%>
        <p class="text-muted">
            No tienes trabajos en ejecución.
        </p>
        <% end %>
    </section>

    <section id="trabajos-pendientes" class="well">
        <h3>Trabajos por evaluar</h3>
        <% if @por_evaluar.size > 0 %>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Trabajo</th>
                    <th>Presupuesto</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <% @por_evaluar.each do |trabajo|
                p = trabajo.presupuesto_contratado
                m = p.mensajes
                %>
                <tr>
                    <td>
                    <p>
                        <%= trabajo.proposito %>
                    </p>
                    <p>
                        <%= link_to 'Ver solicitud', trabajo %>
                    </p></td>
                    <td>
                    <p>
                        <%= link_to((number_to_currency(p.precio_minimo)+" a "+number_to_currency(p.precio_maximo)), p) %>
                    </p>
                    <p>
                        <%= link_to t('extras.mensajes', :count => p.cant_mensajes), presupuesto_path(p, :anchor => "mensajes") %> (<%= m.where(:usuario => :proveedor, :visto => false).size %> sin leer)
                    </p></td>
                    <td style="vertical-align: middle;"><%= link_to "Evaluar", new_trabajo_evaluacion_path(trabajo), :class => "btn btn-success" if trabajo.evaluacion.nil?%></td>
                </tr>
                <% end %>
            </tbody>
        </table>
        <% else%>
        <p class="text-muted">
            ¡Excelente! No tienes trabajos sin evaluar.
        </p>
        <% end %>
    </section>
</div>

app/views/solicitantes/perfil.html.erb
<div class="page-header">
  <h1>Tu perfil</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Nombre y apellido:</strong></dt>
  <dd><%= @solicitante["datos"]["nombre"] %> <%= @solicitante["datos"]["apellido"] %></dd>
  <dt><strong>C&eacute;dula:</strong></dt>
  <dd><%= @solicitante["perfil"]["cedula"] %></dd>
  <dt><strong>Correo electr&oacute;nico:</strong></dt>
  <dd><%= @solicitante["datos"]["email"] %></dd>
  <dt><strong>Sexo:</strong></dt>
  <dd><%= @solicitante["datos"]["sexo"] %></dd>
  <dt><strong>Fecha de nacimiento</strong></dt>
  <dd><%= @solicitante["datos"]["fecha_nacimiento"] %></dd>
  <dt><strong>Tel&eacute;fono fijo:</strong></dt>
  <dd><%= @solicitante["datos"]["telefono_fijo"] %></dd>
  <dt><strong>Tel&eacute;fono m&oacute;vil:</strong></dt>
  <dd><%= @solicitante["datos"]["telefono_movil"] %></dd>
  <dt><strong>Tel&eacute;fono alternativo:</strong></dt>
  <dd><%= @solicitante["datos"]["telefono_alt"] %></dd>
  <dt><strong>Direcci&oacute;n:</strong></dt>
  <dd><%= @solicitante["perfil"]["direccion"] %></dd>
  <dt><strong>Punto de referencia:</strong></dt>
  <dd><%= @solicitante["perfil"]["punto_referencia"] %></dd>
  <dt><strong>Solicitudes realizadas:</strong></dt>
  <dd><%= @solicitante["perfil"]["solicitudes_realizadas"] %></dd>
  <dt><strong>Trabajos recibidos:</strong></dt>
  <dd><%= @solicitante["perfil"]["trabajos_recibidos"] %></dd>
</dl>